baseURL = "https://berater-sofort.de"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "berater-sofort.de | Berater für Ihr Problem in 24H"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 - berater-sofort.de\n\nberater-sofort.de ist eine Marke von Kuron Consulting UG\n\nDesigned by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "Über uns"
pre = "#"
url = "about"
weight = 1
[[Languages.en.menu.main]]
name = "Services"
pre = "#"
url = "services"
weight = 2
[[Languages.en.menu.main]]
name = "Pricing"
pre = "#"
url = "pricing"
weight = 5
[[Languages.en.menu.main]]
name = "Kontakt"
pre = "#"
url = "contact"
weight = 7
[params]
author = "sofort-berater.de"
description = "Berater für Ihr Problem in 24h | Schnell, diskret, unkonventionell"
google_analytics_id = "UA-187267836-1"
logo = "images/title_light.png"
post_share = true
social = []
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/preloader_small.gif"
